fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: App\Entity\User
    # Mailer is disabled
    from_email:
        address: 'gitki@example.com'
        sender_name: 'GitKi'
    service:
        mailer: fos_user.mailer.noop
