security:

    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'email'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users
            form_login:
                enable_csrf: true
                default_target_path: app.index
                login_path: app.login
                check_path: app.login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            logout:
                path: app.logout

    access_control:
        -   path: ^/login
            roles: PUBLIC_ACCESS
        -   path: ^/connect
            roles: PUBLIC_ACCESS
        -   path: ^/loggedout
            roles: PUBLIC_ACCESS

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
