parameters:
#    ddr_gitki_base.example.class: Dontdrinkandroot\Gitki\BaseBundle\Example

services:

    ddr.gitki.twig.gitki_extension:
        class: Dontdrinkandroot\Gitki\BaseBundle\Twig\GitkiExtension
        tags:
            - { name: twig.extension }

    ddr.gitki.repository.git:
        class: Dontdrinkandroot\Gitki\BaseBundle\Repository\GitRepository
        arguments: [%ddr_gitki_base.repository_path%]

    ddr.gitki.service.markdown:
        class: Dontdrinkandroot\Gitki\MarkdownBundle\Service\RepositoryAwareMarkdownService
        arguments: [@ddr.gitki.repository.git]

    ddr.gitki.service.lock:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\LockService
        arguments: [@ddr.gitki.repository.git]

    ddr.gitki.service.wiki:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\EventDispatchingWikiService
        arguments:
            - @ddr.gitki.repository.git
            - @ddr.gitki.service.lock
            - @ddr.gitki.service.markdown
            - @event_dispatcher

    ddr.gitki.service.action_handler.directory:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\ActionHandler\DirectoryActionHandlerService

    ddr.gitki.service.action_handler.file:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\ActionHandler\FileActionHandlerService

    # DIRECTORY HANDLERS

    ddr.gitki.action_handler.directory.list:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\Directory\ListDirectoryActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory }
            -  { name: ddr.gitki.action_handler.directory, action: list }

    ddr.gitki.action_handler.directory.index:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\Directory\DirectoryIndexActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory, action: index }

    ddr.gitki.action_handler.directory.add_folder:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\Directory\AddFolderDirectoryActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory, action: addfolder }

    ddr.gitki.action_handler.directory.delete:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\Directory\DeleteDirectoryActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory, action: delete }

    ddr.gitki.action_handler.directory.upload_file:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\Directory\UploadFileActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory, action: upload }

    # FILE HANDLERS

    ddr.gitki.action_handler.file.serve:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\File\ServeFileActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.file }

    ddr.gitki.action_handler.file.delete:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\File\DeleteFileActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.file, action: delete }

    ddr.gitki.action_handler.file.rename:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\File\RenameFileActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.file, action: rename }

    ddr.gitki.action_handler.file.history:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\File\FileHistoryActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.file, action: history }

    ddr.gitki.action_handler.file.hold_lock:
        class: Dontdrinkandroot\Gitki\BaseBundle\ActionHandler\File\HoldLockActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.file, action: holdlock }
