parameters:
#    ddr_gitki_base.example.class: Dontdrinkandroot\Gitki\BaseBundle\Example

services:

    ddr.gitki.repository.user:
        class:           Dontdrinkandroot\Gitki\BaseBundle\DoctrineUserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - Dontdrinkandroot\Gitki\BaseBundle\Entity\User

    ddr.gitki.twig.gitki_extension:
        class: Dontdrinkandroot\Gitki\BaseBundle\Twig\GitkiExtension
        tags:
            - { name: twig.extension }

    ddr.gitki.security.response_handler.github:
        class: Dontdrinkandroot\Gitki\BaseBundle\Security\GitHubResponseHandler

    ddr.gitki.security.response_handler.google:
        class: Dontdrinkandroot\Gitki\BaseBundle\Security\GoogleResponseHandler

    ddr.gitki.repository.git:
        class: Dontdrinkandroot\Gitki\BaseBundle\Repository\GitRepository
        arguments: [%ddr_gitki_base.repository_path%]

    ddr.gitki.service.user:
        #class: Dontdrinkandroot\Gitki\BaseBundle\Service\VolatileUserService
        #arguments: [%ddr_gitki_base.users%]
       class: Dontdrinkandroot\Gitki\BaseBundle\Service\DoctrineUserService
       arguments: [@ddr.gitki.repository.user, @security.encoder_factory, @security.secure_random]

    ddr.gitki.service.markdown:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\Markdown\RepositoryAwareMarkdownService
        arguments: [@ddr.gitki.repository.git]

    ddr.gitki.service.wiki:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\WikiService
        arguments: [@ddr.gitki.repository.git, @ddr.gitki.service.markdown, @event_dispatcher]

    ddr.gitki.security.user_provider:
        class: Dontdrinkandroot\Gitki\BaseBundle\Security\UserProvider
        arguments: [@ddr.gitki.service.user]
        calls:
            - [registerHandler, [@ddr.gitki.security.response_handler.github]]
            - [registerHandler, [@ddr.gitki.security.response_handler.google]]

    ddr.gitki.service.action_handler.directory:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\ActionHandler\Directory\DirectoryActionHandlerService

    # DIRECTORY HANDLERS

    ddr.gitki.service.action_handler.directory.list:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\ActionHandler\Directory\ListDirectoryActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory }
            -  { name: ddr.gitki.action_handler.directory, action: list }

    ddr.gitki.service.action_handler.directory.index:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\ActionHandler\Directory\DirectoryIndexActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory, action: index }

    ddr.gitki.service.action_handler.directory.add_folder:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\ActionHandler\Directory\AddFolderDirectoryActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory, action: addfolder }

    ddr.gitki.service.action_handler.directory.delete:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\ActionHandler\Directory\DeleteDirectoryActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory, action: delete }

    ddr.gitki.service.action_handler.directory.upload_file:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\ActionHandler\Directory\UploadFileActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory, action: upload }

    ddr.gitki.service.action_handler.directory.add_page:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\ActionHandler\Directory\AddPageActionHandler
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            -  { name: ddr.gitki.action_handler.directory, action: addpage }