imports:
    resource: "@DdrGitkiBaseBundle/Resources/config/routing.yml"

ddr_gitki_elasticsearch_search:
    path:   /search/
    defaults: { _controller: DdrGitkiElasticsearchBundle:Search:search }