parameters:

services:

    ddr.gitki.repository.elasticsearch:
        class:  Net\Dontdrinkandroot\Gitki\ElasticSearchBundle\Repository\ElasticSearchRepository
        arguments: [%ddr_gitki_elastic_search.host%, %ddr_gitki_elastic_search.port%, %ddr_gitki_base.name%]
        tags:
            - { name: kernel.event_listener, event: ddr.gitki.wiki.markdown_document.saved, method: onMarkdownDocumentSaved }
            - { name: kernel.event_listener, event: ddr.gitki.wiki.markdown_document.deleted, method: onMarkdownDocumentDeleted }