filter:
    excluded_paths:
        - 'app/*'
        - 'bin/*'
        - 'var/*'
        - 'web/*'
        - 'src/*/*/*Bundle/Tests'
tools:
    php_code_coverage: false
    external_code_coverage:
        runs: 1
        timeout: 1200
checks:
    php:
        code_rating: true
        duplication: true
