filter:
    excluded_paths:
        - 'app/*'
        - 'bin/*'
        - 'var/*'
        - 'web/*'
checks:
    php:
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        parameter_doc_comments: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: ''
        no_goto: true
        no_long_variable_names:
            maximum: '30'
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        line_length:
            max_length: '120'
        function_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        fix_line_ending: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_unnecessary_concatenation: true
        avoid_multiple_statements_on_same_line: true
        avoid_todo_comments: true
        avoid_fixme_comments: true
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
