language: php

php:
    - 7.1
    - 7.2
    - 7.3

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/yarn

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer install
    - git config --global user.email "gitki@dontdrinkandroot.net"
    - git config --global user.name "GitKi"
    - yarn install
    - yarn encore dev

script:
    - SYMFONY_DEPRECATIONS_HELPER="weak" bin/phpunit
