language: php

php:
    - 5.5

before_script:
    - cp app/config/parameters.yml.test app/config/parameters.yml
    - composer install
    - bin/console doctrine:schema:create
    - git config --global user.email "gitki@dontdrinkandroot.net"
    - git config --global user.name "GitKi"

script:
    - bin/phpunit -c app/
