language: php

php:
    - 7.3
    - 7.4

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/yarn

before_script:
    - composer install
    - git config --global user.email "gitki@dontdrinkandroot.net"
    - git config --global user.name "GitKi"
    - yarn install
    - yarn encore dev

script:
    - SYMFONY_DEPRECATIONS_HELPER="weak" bin/phpunit
