imports:
    -
        resource: parameters.yml
    -
        resource: security.yml
framework:
    translator:
        fallback: '%locale%'
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: null
    form: null
    csrf_protection: null
    validation:
        enable_annotations: true
    templating:
        engines:
            - twig
    default_locale: en
    trusted_hosts: null
    trusted_proxies: null
    session:
        handler_id: null
    fragments: null
    http_method_override: true
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles: {  }
    filters:
        cssrewrite: null
doctrine:
    dbal:
        driver: pdo_sqlite
        charset: UTF8
        path: '%kernel.root_dir%/../var/data/data.db3'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
braincrafted_bootstrap:
    auto_configure:
        assetic: false
hwi_oauth:
    firewall_names: [secured_area]
    fosub:
        properties: null
    connect: null
fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: Dontdrinkandroot\Gitki\WebBundle\Entity\User
    service:
        mailer: fos_user.mailer.noop
ddr_gitki:
    name: '%name%'
    repository_path: '%repository_path%'
