imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator:
        fallback: '%locale%'
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines:
            - twig
    default_locale: en
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: ~
    fragments: ~
    http_method_override: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles: [ "DdrGitkiBundle", "DdrGitkiWebBundle" ]
    filters:
        cssrewrite: ~
        lessphp:
            file: '%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php'
            apply_to: '\.less$'
            formatter: "compressed"
            preserve_comments: false

doctrine:
    dbal:
        driver: pdo_sqlite
        charset: UTF8
        path: '%kernel.root_dir%/../var/data/data.db3'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

braincrafted_bootstrap:
    auto_configure:
        assetic: false

hwi_oauth:
    firewall_names: [secured_area]
    fosub:
        properties: ~
    connect: ~
