security:
    providers:
        gitki_user_provider:
            id: ddr.gitki.security.user_Provider

    firewalls:
        secured_area:
            anonymous: ~
            logout:
                path:   /logout
                target: /
            oauth:
                resource_owners:
                    github:          "/login/check-github"
                login_path:        /connect/github
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: ddr.gitki.security.user_Provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: \.md/edit$, roles: ROLE_OAUTH_USER }
