security:
    providers:
        gitki_user_provider:
            id: ddr.gitki.security.user_provider

    role_hierarchy:
        ROLE_ADMIN: ROLE_COMMITER
        ROLE_COMMITER: ROLE_WATCHER

    firewalls:
        secured_area:
            anonymous: ~
            logout:
                path:   /logout
                target: /loggedout
            oauth:
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                oauth_user_provider:
                    service: ddr.gitki.security.user_provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/loggedout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        ## Only logged in users may see content
        #- { path: ^/, roles: ROLE_USER }
        ## Only watchers may see content
        #- { path: ^/, roles: ROLE_WATCHER }
        ## All users may see content
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
