parameters:

services:

    ddr.gitki.repository.elasticsearch:
        class:  Dontdrinkandroot\Gitki\ElasticsearchBundle\Repository\ElasticsearchRepository
        arguments: [%ddr_gitki_elasticsearch.host%, %ddr_gitki_elasticsearch.port%,  %ddr_gitki_elasticsearch.index_name%]
        tags:
            - { name: kernel.event_listener, event: ddr.gitki.wiki.markdown_document.saved, method: onMarkdownDocumentSaved }
            - { name: kernel.event_listener, event: ddr.gitki.wiki.markdown_document.deleted, method: onMarkdownDocumentDeleted }

    ddr.gitki.service.wiki:
        class: Dontdrinkandroot\Gitki\ElasticsearchBundle\Service\ElasticsearchWikiService
        arguments: [@ddr.gitki.repository.git, @ddr.gitki.service.markdown, @event_dispatcher, @ddr.gitki.repository.elasticsearch]