#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app.login:
    path: /login
    controller: App\Controller\Web\Security\LoginAction

app.logout:
    path: /logout

login_manual:
    path:     /login/manual
    methods:  [GET]
    defaults: { _controller: App\Controller\DefaultController:loginAction }

ddr_gitki_loggedout:
    path:   /loggedout
    methods:  [GET]
    defaults: { _controller: App\Controller\DefaultController:loggedoutAction }

app.index:
    path: /
    methods: [ GET ]
    defaults: { _controller: App\Controller\DefaultController:indexAction }

ddr_gitki.user.list:
    path: /users/
    defaults:
        _controller: App\Controller\UserController:listAction

ddr_gitki.user.edit:
    path: /users/{id}/edit
    defaults:
        _controller: App\Controller\UserController:editAction

ddr_gitki.user.delete:
    path: /users/{id}/delete
    defaults:
        _controller: App\Controller\UserController:deleteAction

ddr_gitki_base:
    resource: "@DdrGitkiBundle/Resources/config/routing.yaml"
