#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    resource: '@FOSUserBundle/Resources/config/routing/change_password.xml'
    prefix: /user

fos_user_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /user/profile

login_manual:
    path:     /login/manual
    methods:  [GET]
    defaults: { _controller: App\Controller\DefaultController:loginAction }

ddr_gitki_loggedout:
    path:   /loggedout
    methods:  [GET]
    defaults: { _controller: App\Controller\DefaultController:loggedoutAction }

ddr_gitki_base_homepage:
    path:     /
    methods:  [GET]
    defaults: { _controller: App\Controller\DefaultController:indexAction }

ddr_gitki.user.list:
    path: /users/
    defaults:
        _controller: App\Controller\UserController:listAction

ddr_gitki.user.edit:
    path: /users/{id}/edit
    defaults:
        _controller: App\Controller\UserController:editAction

ddr_gitki.user.delete:
    path: /users/{id}/delete
    defaults:
        _controller: App\Controller\UserController:deleteAction

ddr_gitki_base:
    resource: "@DdrGitkiBundle/Resources/config/routing.yml"
