ddr_gitki_base_homepage:
    path:     /
    defaults: { _controller: DdrGitkiBaseBundle:Default:index }

ddr_gitki_wiki_directory:
    path:   /wiki/{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:directory, path: / }
    requirements:
        path: .*/|

ddr_gitki_wiki_file:
    path:   /wiki/{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:file }
    requirements:
        path: .+

ddr_gitki_github_issues:
    path:   /github/issues
    defaults: { _controller: DdrGitkiBaseBundle:Github:issues }

ddr_gitki_github_issue_create:
    path:   /github/issues/create
    defaults: { _controller: DdrGitkiBaseBundle:Github:createIssue }