hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

google_login:
    pattern: /login/check-google

github_login:
    pattern: /login/check-github

logout:
    path:   /logout

login_manual:
    path:     /login/manual
    defaults: { _controller: DdrGitkiBaseBundle:Default:login }

ddr_gitki_base_homepage:
    path:     /
    defaults: { _controller: DdrGitkiBaseBundle:Default:index }

ddr_gitki_loggedout:
    path:   /loggedout
    defaults: { _controller: DdrGitkiBaseBundle:Default:loggedout }

ddr_gitki_history:
    path:   /history
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:history }

ddr_gitki_wiki_directory:
    path:   /wiki{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:directory }
    requirements:
        path: .*/

ddr_gitki_wiki_file:
    path:   /wiki{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:file }
    requirements:
        path: .+