ddr_gitki_base_homepage:
    path:     /
    defaults: { _controller: DdrGitkiBaseBundle:Default:index }

ddr_gitki_wiki_page_edit:
    path:   /wiki/{path}/edit
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:pageEdit }
    requirements:
        path: .+\.md

ddr_gitki_wiki_page_delete:
    path:   /wiki/{path}/delete
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:deletePage }
    requirements:
        path: .+\.md

ddr_gitki_wiki_page:
    path:   /wiki/{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:page }
    requirements:
        path: .+\.md

ddr_gitki_wiki_directory:
    path:   /wiki/{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:listDirectory }
    requirements:
        path: .*/

ddr_gitki_wiki_file_rename:
    path:   /wiki/{path}/rename
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:renameFile }
    requirements:
        path: .+

ddr_gitki_wiki_file_show:
    path:   /wiki/{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:showFile }
    requirements:
        path: .+

ddr_gitki_wiki_base_directory:
    path:   /wiki/
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:listDirectory }