ddr_gitki_base_homepage:
    path:     /
    defaults: { _controller: DdrGitkiBaseBundle:Default:index }

ddr_gitki_wiki_directory:
    path:   /wiki/{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:directory }
    requirements:
        path: .*/

ddr_gitki_wiki_file:
    path:   /wiki/{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:file }
    requirements:
        path: .+

ddr_gitki_wiki_base_directory:
    path:   /wiki/
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:directory, path: / }