parameters:
#    ddr_gitki_base.example.class: Net\Dontdrinkandroot\Gitki\BaseBundle\Example

services:
    ddr.gitki.security.user_Provider:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Security\UserProvider

    ddr.gitki.service.wiki:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Service\WikiService
        arguments: [%repository_path%]

