parameters:
#    ddr_gitki_base.example.class: Net\Dontdrinkandroot\Gitki\BaseBundle\Example

services:
    ddr.gitki.security.user_Provider:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Security\UserProvider
#    ddr_gitki_base.example:
#        class: %ddr_gitki_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


