parameters:
#    ddr_gitki_base.example.class: Net\Dontdrinkandroot\Gitki\BaseBundle\Example

services:

    ddr.gitki.security.response_handler.github:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Security\GitHubResponseHandler
        arguments:
            - %ddr_gitki_base.github_users_admin%
            - %ddr_gitki_base.github_users_commit%
            - %ddr_gitki_base.github_users_watch%

    ddr.gitki.security.response_handler.google:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Security\GoogleResponseHandler
        arguments:
            - %ddr_gitki_base.google_users_admin%
            - %ddr_gitki_base.google_users_commit%
            - %ddr_gitki_base.google_users_watch%


    ddr.gitki.security.user_provider:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Security\UserProvider
        calls:
            - [registerHandler, [@ddr.gitki.security.response_handler.github]]
            - [registerHandler, [@ddr.gitki.security.response_handler.google]]


    ddr.gitki.repository.git:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Repository\GitRepository
        arguments: [%repository_path%]

    ddr.gitki.service.markdown:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Service\RepositoryAwareMarkdownService
        arguments: [@ddr.gitki.repository.git]

    ddr.gitki.service.wiki:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Service\WikiService
        arguments: [@ddr.gitki.repository.git, @ddr.gitki.service.markdown, @event_dispatcher]

