parameters:
#    ddr_gitki_base.example.class: Net\Dontdrinkandroot\Gitki\BaseBundle\Example

services:

    ddr.gitki.repository.user:
        class:           Net\Dontdrinkandroot\Gitki\BaseBundle\DoctrineUserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - Net\Dontdrinkandroot\Gitki\BaseBundle\Entity\User

    ddr.gitki.twig.gitki_extension:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Twig\GitkiExtension
        tags:
            - { name: twig.extension }

    ddr.gitki.security.response_handler.github:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Security\GitHubResponseHandler

    ddr.gitki.security.response_handler.google:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Security\GoogleResponseHandler

    ddr.gitki.repository.git:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Repository\GitRepository
        arguments: [%ddr_gitki_base.repository_path%]

    ddr.gitki.service.user:
        #class: Net\Dontdrinkandroot\Gitki\BaseBundle\Service\VolatileUserService
        #arguments: [%ddr_gitki_base.users%]
       class: Net\Dontdrinkandroot\Gitki\BaseBundle\Service\DoctrineUserService
       arguments: [@ddr.gitki.repository.user, @security.encoder_factory, @security.secure_random]

    ddr.gitki.service.markdown:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Service\Markdown\RepositoryAwareMarkdownService
        arguments: [@ddr.gitki.repository.git]

    ddr.gitki.service.wiki:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Service\WikiService
        arguments: [@ddr.gitki.repository.git, @ddr.gitki.service.markdown, @event_dispatcher]

    ddr.gitki.security.user_provider:
        class: Net\Dontdrinkandroot\Gitki\BaseBundle\Security\UserProvider
        arguments: [@ddr.gitki.service.user]
        calls:
            - [registerHandler, [@ddr.gitki.security.response_handler.github]]
            - [registerHandler, [@ddr.gitki.security.response_handler.google]]
