services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Dontdrinkandroot\Gitki\WebBundle\:
        resource: '../../../../src/WebBundle/*'
        exclude:  '../../../../src/WebBundle/{Entity,Migrations,Tests}'
